[package]
name = "dragon-api"
version = "0.0.1"
authors = ["Igor-Khan <khanigot@gmil.com>"]
edition = "2018"

[dependencies]
reqwest = "0.11"
tokio = { version = "1", features = ["full"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tide = "0.16.0"

